# Generated by Django 2.2.3 on 2019-09-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0002_auto_20190829_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='led',
        ),
        migrations.AddField(
            model_name='status',
            name='moisture',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='status',
            name='title',
            field=models.CharField(default='unkhown', max_length=300),
        ),
    ]
