# Generated by Django 2.2.3 on 2019-09-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0005_auto_20190907_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
