# Generated by Django 2.2.3 on 2019-09-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0007_auto_20190922_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='moisture',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
